# Generated by Django 5.2.3 on 2025-06-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
