# Generated by Django 5.2.3 on 2025-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_full_na_6ea9f7_idx',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='students_st_name_0bae46_idx'),
        ),
    ]
