# Generated by Django 5.2.3 on 2025-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
