# Generated by Django 5.2.3 on 2025-06-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('students', '0003_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-received_time']},
        ),
        migrations.AlterField(
            model_name='parcel',
            name='received_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='parcels_par_status_469061_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['received_time'], name='parcels_par_receive_4be07a_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['student'], name='parcels_par_student_41713b_idx'),
        ),
    ]
