# Generated by Django 5.2.3 on 2025-06-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('students', '0002_student_block_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='picked_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='students.student'),
        ),
    ]
