# Generated by Django 5.2.3 on 2025-06-15 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_alter_parcel_options_and_more'),
        ('students', '0003_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='tracking_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['tracking_id'], name='parcels_par_trackin_d26a43_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='parcels_par_status_469061_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['created_at'], name='parcels_par_created_456da3_idx'),
        ),
    ]
