# Generated by Django 5.2.3 on 2025-06-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hosteldrop/'),
        ),
    ]
