# Generated by Django 5.2.3 on 2025-06-17 02:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_parcel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
