# Generated by Django 5.2.3 on 2025-06-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_alter_parcel_image'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel'),
        ),
    ]
