# Generated by Django 5.2.3 on 2025-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_helprequest_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
